### ISSUE TITLE
1.19.2 - Crash on Startup - Incompatibility with Ferritecore

### ISSUE THREAD

**Issue by DracoExE** [Globox1997/InmisAddon#3]
When launching the game, it crashes on startup when having Ferritecore and this mod. If I remove this mod while keeping ferritecore, the game launches normally (also, if I remove ferritecore and keep this mod, the game also launches without crashing).

Fabric Api: 0.60.0
Cloth Config: 8.0.75
Inmis: 2.7.0
InmisAddon: 1.0.0
FerriteCore: 5.0.0

Crash Log:
[crash-2022-08-31_12.06.52-client.txt](https://github.com/Globox1997/InmisAddon/files/9463156/crash-2022-08-31_12.06.52-client.txt)

**Comment by Globox1997** [comment]
Probably fixed with [https://github.com/Globox1997/InmisAddon/commit/fb2699cbc67277930432a770b3aac34382e86b6f](https://github.com/Globox1997/InmisAddon/commit/fb2699cbc67277930432a770b3aac34382e86b6f)

**Comment by DracoExE** [comment]
> 

Tested the new version of this mod and it worked!
