### ISSUE TITLE
InmisAddon thinks fabric-api is missing

### ISSUE THREAD

**Issue by Rhys1022076** [Globox1997/InmisAddon#5]
With inmisaddon-1.0.1, launching the game fails and Fabric Loader 0.14.9 shows an error:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, any version.
Unmet dependency listing:
	 - Mod 'InmisAddon' (inmisaddon) 1.0.1 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

This is using a small custom modpack to play 1.19 using Fabric 0.14.9 - fabric-api-0.58.0+1.19.jar is definitely included.

**Comment by Globox1997** [comment]
What happens if you use the latest fabric api?

**Comment by Opus185** [comment]
Having the same issue. It appears to not work with a later version of minecraft like 1.19.1. The other issue could be that it does not work with Fabric API 58.5 but that is the latest version for 1.19.1 so in my mind, same issue that it does not work with a MC version older than 1.19.2.

My testing:

I set up two new basic MC installs of version 1.19.2 and 1.19.1. I installed latest version of fabric and then only added three mods as shown below.

mod directory of version 1.19.2:

![Inmisaddon 1 19 2](https://user-images.githubusercontent.com/113369257/190675978-ed90fb48-1512-42ef-8468-47ec93293cd6.png)

mod directory of version 1.19.1:

![Inmisaddon 1 19 1](https://user-images.githubusercontent.com/113369257/190676000-52dc800e-83ee-4772-856d-d81fdf740298.png)


It worked for the version 1.19.2 but not the version 1.19.1. I get the same error as listed above from Rhys10220976 on 1.19.1:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-api, any version.
Unmet dependency listing:
	 - Mod 'InmisAddon' (inmisaddon) 1.0.1 requires any version of fabric-api, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Globox1997** [comment]
Yes it is an issue with the api, fabric itself changed the id of the api to fabric-api.

**Comment by Opus185** [comment]
Is that something you can/are willing to address for the MC 1.19.1 version?

**Comment by Globox1997** [comment]
I mean why not updating to 1.19.2?

**Comment by TheSnipps** [comment]
I'm  having same problem with 1.19.  I am unable to update to 1.19.1 or 2 because of other conflicting mods not working in those versions.  Is there a way to get it to work with Fabric api 0.57.0 or 0.58.0?

**Comment by TheSnipps** [comment]
The solution that worked for me was simply going to the fabric.mod.json file with notepad and at the bottom where it says "fabric-api": I just changed to say "fabric": and it worked.

**Comment by Spuntamatite** [comment]
> The solution that worked for me was simply going to the fabric.mod.json file with notepad and at the bottom where it says "fabric-api": I just changed to say "fabric": and it worked.

I don't understant where the .json should be, I only have .jar files in the mod folder.

**Comment by Globox1997** [comment]
Fixed with a later version, out of time reasons I only work on the latest version of my mods.
