### ISSUE TITLE
Crashes without Trinkets also installed

### ISSUE THREAD

**Issue by BowTieDaniels** [Globox1997/InmisAddon#6]
When using the mod without Trinkets any backpack that is not the Frayed Backpack caused the client to crash. If used on a server is also crashes any other players nearby. Players not using the addon are not impacted.

Adding the Trinkets mod resolves the issue and works normally.

I am currently on 1.19.2

Here are the mods I have tested with:
Fabric API 0.60.0
Cloth API 4.0.65
Inmis 2.7.0
InmisAddon 1.0.1

Fixed when using Trinkets 3.4.0

[crash-2022-09-18_16.49.16-client.txt](https://github.com/Globox1997/InmisAddon/files/9595218/crash-2022-09-18_16.49.16-client.txt)

**Comment by Globox1997** [comment]
Fixed with [https://github.com/Globox1997/InmisAddon/commit/b9807d92e17d38b6d5b8be57e171dc947509b039](https://github.com/Globox1997/InmisAddon/commit/b9807d92e17d38b6d5b8be57e171dc947509b039)
Thanks for report
